### ISSUE TITLE
Try this :)

### ISSUE THREAD

**Issue by rzmn** [SleekPanther/minimum-weighted-vertex-cover-approximation-algorithm#1]
int vertexCount = 4;
graph1.addEdge(0,1);
graph1.addEdge(0,2);
graph1.addEdge(0,3);
int[] weights = {100, 1, 1, 1};

**Comment by rzmn** [comment]
If we select two adjacent edges, adding three vertices is meaningless, we can always leave two.

**Comment by SleekPanther** [comment]
Good catch. I realized looking back, that I totally messed up the implementation. It was not doing what the pseudocode said at all. Instead of looping over edges, it was looping over vertices and almost all the time adding all vertices instead of actually doing the pricing method.
Please check the latest version as I have rewritten the code and updated the readme.
